RadicalCSG/Chisel.Prototype

Packages/com.chisel.components/Chisel/Components/API.public/BrushMeshAssetFactory/Sphere/BrushFactory.Sphere.cs
Packages/com.chisel.components/Chisel/Components/API.public/BrushMeshAssetFactory/Sphere/CSGSphereDefinition.cs
Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/Sphere/BrushFactory.Sphere.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/CSGSphere/Editor/CSGSphereGeneratorMode.cs

* Refactored sphere mesh creation to BrushMeshFactory
* Implemented sphere tool mode so the button works in the UI

Sphere Tool

---

Packages/com.chisel.editor/Chisel/Editor/Components/Generators/CSGBox/Editor/CSGBoxGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/CSGCylinder/Editor/CSGCylinderEditor.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/CSGCylinder/Editor/CSGCylinderGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/BoxExtrusionHandle.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/ExtrustionHandle.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/ShapeExtrusionHandle.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/SceneHandles/SceneHandles.Radius2D.cs

This PR fixes the following issues 
- #9  "Cylinder resizing only shrinks"
- #7 "Cylinder tool preview does not match generated radius"
- #6 "Box tool does not align correctly with drawing plane"

Fix for cylinder and box tool placement and sizing

---

Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Selection/CSGClickSelectionManager.cs

This PR fixes hovering over planes with mouse unintentionally cycling through all the surfaces beneath it

Fixes hovering over planes unintentionally cycling through surfaces

---

Packages/com.chisel.editor/Chisel/Editor/Editor/CSGUnityEventsManager.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/CSGSceneBottomGUI.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Snapping/SnappingKeyboard.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Settings/CSGEditorSettings.cs

Simplified toolbar to minimal frequently used settings. 
Most of the code for the GUI was replaced, in favor of an approach more appropriate for unity's GUI system.

Toolbar gui

---

Packages/com.chisel.components/Chisel/Components/API.public/Components/Base/CSGGeneratorComponent.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Base/CSGNode.cs

This PR makes it possible to move pivots without the brushes moving with them 
See #1

Fixed pivot movement

---

Packages/com.chisel.components/Chisel/Components/API.private/CSGNodeHierarchyManager.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Containers/Model/Editor/CSGModelEditor.cs

See comments on commits b00d083 & 43df245

Fix deprecation warnings for prefab API

---

Packages/com.chisel.components/Chisel/Components/API.public/Components/Base/CSGNode.cs
Packages/com.chisel.core/Chisel/Core/API.public/BrushMesh.cs
Packages/com.chisel.core/Chisel/Core/API.public/CSGSurfaceIntersection.cs
Packages/com.chisel.core/Chisel/Core/API.public/CSGTreeBrushIntersection.cs
Packages/com.chisel.core/Chisel/Core/Extensions/MathExtensions.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/EditModes/CSGSurfaceEditMode.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Selection/CSGClickSelectionManager.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/Snapping/SceneHandles.Snapping.cs

Simplified some code, put code in utility methods, added some comments to clarify.

Cleaned up surface edit mode

---

Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/PointDrawing.cs

Fix being able to use Axis Gizmo when using a Generator

---

Packages/com.chisel.core/Chisel/Core/API.private/BrushMeshInstance.Private.cs
Packages/com.chisel.core/Chisel/Core/API.private/CSGTreeBrush.Private.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/BrushMesh.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/BrushMeshInstance.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/BrushMeshManager.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGManager.Algorithm.internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGManager.GenerateMesh.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGManager.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGManager.Query.internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGTree.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGTreeBranch.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGTreeBrush.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSGTreeNode.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/Loop.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/BrushMeshInstance.Native.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/CSGManager.Native.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/CSGTree.Native.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/CSGTreeBranch.Native.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/CSGTreeBrush.Native.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/CSGTreeNode.Native.cs
Packages/com.chisel.core/Chisel/Core/API.public/BrushMesh.cs

Renamed USE_INTERNAL_IMPLEMENTATION define to USE_MANAGED_CSG_IMPLEMENTATION

Renamed a define

---

Packages/com.chisel.components/Chisel/Components/API.private/CSGNodeHierarchyManager.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedComponentManager.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedModelMeshManager.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselSharedUnityMeshManager.cs

Somehow some changes didn't end up the refactor PR, so I'm just quickly adding them to avoid issues for everyone

Some changes that where supposed to be in "humongous refactor" #101

---

Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/Capsule/ChiselCapsuleDefinition.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/Capsule/Editor/ChiselCapsuleEditor.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/Capsule/Editor/ChiselCapsuleGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/Components/Generators/Cylinder/Editor/ChiselCylinderGeneratorMode.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/SceneHandles/SceneHandles.Edge1D.cs

Caps can now be resized in scene + generating capsule  will have better caps height by default

Capsule handle improvements

---

Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Base/ChiselNodeDetailsManager.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Base/ChiselNodeEditor.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Containers/ChiselModelEditor.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselBoxGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselCapsuleGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselCylinderGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselExtrudedShapeGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselHemisphereGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselLinearStairsGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselPathedStairsGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselRevolvedShapeGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselSphereGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselSpiralStairsGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselStadiumGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselTorusGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModes/ChiselObjectEditMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModes/ChiselPivotEditMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModes/ChiselShapeEditMode.cs
Packages/com.chisel.editor/Chisel/Editor/EditModes/ChiselSurfaceEditMode.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/ChiselUnityEventsManager.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/DragAndDrop/ChiselDragAndDropMaterial.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/ChiselEditModeGUI.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/ChiselEditModeManager.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Visualization/ChiselOutlineRenderer.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Settings/ChiselEditorSettings.cs

Made the list of edit modes auto discovered instead of hardcoded
This implements #93

Edit modes discovery

---

Packages/com.chisel.editor/Chisel/Editor/Editor/Hierarchy/ChiselHierarchyWindowManager.cs

Fixed active model text being offset in hierarchy

---

Packages/com.chisel.components/Chisel/Components/API.private/CSGHierarchyItem.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedComponentManager.cs
Packages/com.chisel.components/Chisel/Components/API.public/ChiselModelManager.cs
Packages/com.chisel.core/Chisel/Core/API.private/CSGMaterialManager.cs
Packages/com.chisel.core/Chisel/Core/API.private/Native/InternalLogging.cs
Packages/com.chisel.core/Chisel/Core/API.public/CSGDefaults.cs

Fixed some non-editor code being present in runtime code

---

ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt

Added ProjectVersion.txt to project to avoid the upgrade dialog on first start up
Added ProjectSettings.asset to project to avoid compile errors (which a reimport-all fixes)

Fixed first start up issues

---

Packages/com.chisel.editor/Chisel/Editor/EditModes/ChiselPivotEditMode.cs

Real problem is simpleoutlines is broken.

Fixed issue where the pivot tool wouldn't show outlines

---

Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/Box/BrushMeshFactory.Box.cs
Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/ChiselBrushContainer.cs
Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/LinearStairs/BrushFactory.LinearStairs.cs
Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/LinearStairs/ChiselLinearStairsDefinition.cs
Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/PathedStairs/BrushFactory.PathedStairs.cs
Packages/com.chisel.core/Chisel/Core/Extensions/MathExtensions.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Generators/ChiselLinearStairsEditor.cs
Packages/com.chisel.editor/Chisel/Editor/EditModeTools/ChiselLinearStairsGeneratorMode.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/BoxExtrusionHandle.cs
Packages/com.chisel.editor/Chisel/Editor/Editor/Scene/Handles/PointDrawing.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/SceneHandles/SceneHandles.Bounds.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/SceneHandles/SceneHandles.Edge1D.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/SceneHandles/SceneHandles.Slider2D.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/Visualization/SceneLabels.cs
Packages/com.scene.handle.extensions/Handle Extensions/Editor/Visualization/SceneLabels.cs.meta

This PR includes multiple improvements to the linear stairs generation, incl. placement, better/more predictable handle behavior and bug fixes with creation of the actual brushes

Linear stairs improvements

---

Packages/com.chisel.core/Chisel/Core/BrushMeshFactory/Hemisphere/BrushFactory.Hemisphere.cs

Fixed top vertex pointing in wrong direction when hemisphere is created inwards into surface (reversed)

Fix for wrong vertex with inversed hemisphere

---

Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Base/ChiselNodeEditor.cs

Fix for "Group in operation" groups in model

---

Packages/com.chisel.editor/Chisel/Editor/Editor/ChiselUnityEventsManager.cs

This fixes rendering of bottom gui in sceneview / selection b/c of changes how sceneview events work in >=2019.2

Fix for selection/rendering issue until 2019.2

---

Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSG/Jobs/PerformCSGJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/CSG/NativeListArray.cs

Fixed issue where index in array was not created when initialized with capacity 0

Fix issue with NativeListArray

---

Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedComponentManager.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedModelMeshManager.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Containers/ChiselModelGeneratedObjects.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Containers/ChiselModelEditor.cs

Fix for "Unknown Visibility state"

---

README.md

Removed outdated known issue fixed in #268

Removed outdated known issue fixed in #268

---

Packages/packages-lock.json
ProjectSettings/ProjectVersion.txt

update minor unity project version

---

Packages/com.chisel.components/Chisel/Components/API.private/ChiselNodeHierarchyManager.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Base/ChiselGeneratorComponent.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Base/ChiselNode.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Generators/ChiselBrushComponent.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/GeneratorJobPool/GeneratorJobPool.cs
Packages/com.chisel.core/Chisel/Core/API.public/Managed/Managers/CompactHierarchyManager.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Base/ChiselNodeEditor.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Generators/ChiselBrushEditor.cs
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Modifiers/ChiselCompositeEditor.cs

Fixed editing brushes updating everything properly
Fixed hierarchy being updated incorrectly
Fix modifying generator updating brushes
Removed some test stuff from sample scene

Editing bug fixes

---

Packages/com.chisel.components/Chisel/Components/API.private/ChiselGeneratedComponentManager.cs
Packages/com.chisel.components/Chisel/Components/API.private/ChiselNodeHierarchyManager.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Containers/ChiselModel.cs
Packages/com.chisel.components/Chisel/Components/API.public/Components/Generators/ChiselBrushComponent.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/GeneratorJobPool/GeneratorJobPool.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/Managers/CSGManager.UpdateTreeMeshes.cs
Packages/com.chisel.core/Chisel/Core/API.private/Managed/Managers/ChiselMaterialManager.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/BrushMesh/BrushMeshBlob.internal.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/ChiselBlobs/ChiselBlobBuilder.cs
Packages/com.chisel.core/Chisel/Core/API.public/Managed/BrushMesh/BrushMeshManager.Internal.cs
Packages/com.chisel.core/Chisel/Core/API.public/Managed/Managers/CompactHierarchyManager.cs
Packages/com.chisel.core/Chisel/Core/API.public/Managed/Materials/ChiselBrushMaterial.cs
Packages/com.chisel.core/Chisel/Core/API.public/Managed/Materials/ChiselMaterialManager.cs
Packages/com.chisel.core/Chisel/Core/GeneratorBase/IGeneratorHandles.cs
Packages/com.chisel.core/Chisel/Core/Generators/SpiralStairs/BrushFactory.SpiralStairs.cs
Packages/com.chisel.core/package.json
Packages/com.chisel.editor/Chisel/Editor/ComponentEditors/Containers/ChiselModelEditor.cs
Packages/packages-lock.json
ProjectSettings/ProjectVersion.txt
README.md

Updated project version to 2021.2.0b7
Made generator jobs easily switchable between parallel and serial
Fixed crash bug
Fix for "'ChiselModel' has been destroyed ... still trying to access it"
Optimized converting authoring brushmesh to internal brushmesh

More fixes

---

Packages/com.chisel.core/Chisel/Core/API.private/Managed/Managers/CSGManager.UpdateTreeMeshes.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/CreateBlobPolygonsBlobsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/CreateBrushTreeSpacePlanesJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/CreateIntersectionLoopsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/CreateRoutingTableJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/CreateTreeSpaceVerticesAndBoundsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/FillVertexBuffersJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/FindAllBrushIntersectionPairsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/FindBrushPairsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/FindLoopOverlapIntersectionJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/FindModifiedBrushesJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/GatherOutputSurfacesJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/GenerateSurfaceTrianglesJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/MergeTouchingBrushVerticesJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/PerformCSGJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/PrepareBrushPairIntersectionsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/StoreBrushIntersectionsJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/StoreToCacheJob.cs
Packages/com.chisel.core/Chisel/Core/API.private/Unmanaged/Jobs/UpdateTransformationsJob.cs
Packages/com.chisel.core/package.json
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/ProjectVersion.txt
README.md

Removed dependency on AsJobArray since it broke everything

---

Packages/com.chisel.core/Chisel/Core/1.Input/Managers/ChiselDefaultMaterials.cs

Added shadow-only default material to default materials
